name: Report Generation

on:
  pull_request_target:  # Trigger on PRs

jobs:
  hacksaw-report:
    if: github.event.pull_request != null && github.event.pull_request.head.repo.full_name == github.repository
    runs-on: self-hosted
    environment: Test

    env:
      CM_USERNAME: ${{ vars.GH_VAR }}
      CM_TOKEN: ${{ secrets.GH_SECRET }}
      

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Report
        run: |
          echo "STARTING HACKSAW REPORT JOB"
          clonedRepoPath=$(pwd)
          echo $clonedRepoPath
          echo ${CM_USERNAME}
          echo ${{github.event.pull_request.head.repo.full_name}}
          echo ${{github.repository}}
          CITY="Chennai"
          curl -s "https://api.openweathermap.org/data/2.5/weather?q=$CITY&appid=${CM_TOKEN}&units=metric" | jq
